POPB_RALSO
>POPB_RALSO#secreted#extracellular region GO:0005576(IEA);
 Identities = 174/174 (100%), Positives = 174/174 (100%)

Query: 1   MSHSKIKAGGHGSSGIGNDFTPAKTPAPATPAPQSQQVNDLLGRGVGNALNKSNLGSDSQ 60
           MSHSKIKAGGHGSSGIGNDFTPAKTPAPATPAPQSQQVNDLLGRGVGNALNKSNLGSDSQ
Sbjct: 1   MSHSKIKAGGHGSSGIGNDFTPAKTPAPATPAPQSQQVNDLLGRGVGNALNKSNLGSDSQ 60

Query: 61  TWTPGSTMVSLKSRSSSSHKPDTGGDTKPDSTSGGKRKRDDETDPNAETEGGKKKKKRDD 120
           TWTPGSTMVSLKSRSSSSHKPDTGGDTKPDSTSGGKRKRDDETDPNAETEGGKKKKKRDD
Sbjct: 61  TWTPGSTMVSLKSRSSSSHKPDTGGDTKPDSTSGGKRKRDDETDPNAETEGGKKKKKRDD 120

Query: 121 ENDSSQAGGAGSSAGSSGSPEDALMNIALQRAIQRQTQTRQKMQEAMKIKDDDD 174
           ENDSSQAGGAGSSAGSSGSPEDALMNIALQRAIQRQTQTRQKMQEAMKIKDDDD
Sbjct: 121 ENDSSQAGGAGSSAGSSGSPEDALMNIALQRAIQRQTQTRQKMQEAMKIKDDDD 174


