PSTA_DICDI
>PSTA_DICDI#secreted#extracellular matrix GO:0031012(TAS);
 Identities = 1053/1053 (100%), Positives = 1053/1053 (100%)

Query: 1    MNKIYLILILFTFVGIILANVEKAEVSCTCDENCNDGNKCTLDKCNNGCCSNTPININDN 60
            MNKIYLILILFTFVGIILANVEKAEVSCTCDENCNDGNKCTLDKCNNGCCSNTPININDN
Sbjct: 1    MNKIYLILILFTFVGIILANVEKAEVSCTCDENCNDGNKCTLDKCNNGCCSNTPININDN 60

Query: 61   DECTVDTCNPKTGISHTPVNCDDGNSCTADSCLCGKGCQHVPIACDDNNACTVDSCSNST 120
            DECTVDTCNPKTGISHTPVNCDDGNSCTADSCLCGKGCQHVPIACDDNNACTVDSCSNST
Sbjct: 61   DECTVDTCNPKTGISHTPVNCDDGNSCTADSCLCGKGCQHVPIACDDNNACTVDSCSNST 120

Query: 121  GCCHTPLSCDDNNPCTVDSCSNSTGCCHTPINVDDHNACTEDKCTQSGGVTHTPIACDDK 180
            GCCHTPLSCDDNNPCTVDSCSNSTGCCHTPINVDDHNACTEDKCTQSGGVTHTPIACDDK
Sbjct: 121  GCCHTPLSCDDNNPCTVDSCSNSTGCCHTPINVDDHNACTEDKCTQSGGVTHTPIACDDK 180

Query: 181  NACTVDSCSNSTGCCHTPLSCDDNNACTVDSCSNSTGCVHTPINVDDHNACTEDKCTQSG 240
            NACTVDSCSNSTGCCHTPLSCDDNNACTVDSCSNSTGCVHTPINVDDHNACTEDKCTQSG
Sbjct: 181  NACTVDSCSNSTGCCHTPLSCDDNNACTVDSCSNSTGCVHTPINVDDHNACTEDKCTQSG 240

Query: 241  GVTHTPIACDDKNACTADSCSNSTGCCHTPITCDDNNACTVDSCSNSTGCCHTPINVDDN 300
            GVTHTPIACDDKNACTADSCSNSTGCCHTPITCDDNNACTVDSCSNSTGCCHTPINVDDN
Sbjct: 241  GVTHTPIACDDKNACTADSCSNSTGCCHTPITCDDNNACTVDSCSNSTGCCHTPINVDDN 300

Query: 301  NACTEDKCTQSGGVTHTPIACDDKNACTVDSCSNSTGCVHTPLACDDKNPCTVDSCSNST 360
            NACTEDKCTQSGGVTHTPIACDDKNACTVDSCSNSTGCVHTPLACDDKNPCTVDSCSNST
Sbjct: 301  NACTEDKCTQSGGVTHTPIACDDKNACTVDSCSNSTGCVHTPLACDDKNPCTVDSCSNST 360

Query: 361  GCCHTPINVDDNNACTEDKCTQSGGVTHTPINCDDNNKCTVDSCSNSTGCCHTPMSCDDN 420
            GCCHTPINVDDNNACTEDKCTQSGGVTHTPINCDDNNKCTVDSCSNSTGCCHTPMSCDDN
Sbjct: 361  GCCHTPINVDDNNACTEDKCTQSGGVTHTPINCDDNNKCTVDSCSNSTGCCHTPMSCDDN 420

Query: 421  NPCTVDSCSNSTGCVHTPINVDDNNACTEDKCTQNGGVTHTPIACDDKNACTVDSCSNST 480
            NPCTVDSCSNSTGCVHTPINVDDNNACTEDKCTQNGGVTHTPIACDDKNACTVDSCSNST
Sbjct: 421  NPCTVDSCSNSTGCVHTPINVDDNNACTEDKCTQNGGVTHTPIACDDKNACTVDSCSNST 480

Query: 481  GCCHTPLKCDDNNACTVDSCSNSTGCVHTPINVDDNNACTEDKCTQSGGVTHTPISCDDK 540
            GCCHTPLKCDDNNACTVDSCSNSTGCVHTPINVDDNNACTEDKCTQSGGVTHTPISCDDK
Sbjct: 481  GCCHTPLKCDDNNACTVDSCSNSTGCVHTPINVDDNNACTEDKCTQSGGVTHTPISCDDK 540

Query: 541  NPCTIDSCSNSTGCVHTPMSCDDRNPCTSDFCSWEKGCQHVALSCNDFNACTMDSCSNST 600
            NPCTIDSCSNSTGCVHTPMSCDDRNPCTSDFCSWEKGCQHVALSCNDFNACTMDSCSNST
Sbjct: 541  NPCTIDSCSNSTGCVHTPMSCDDRNPCTSDFCSWEKGCQHVALSCNDFNACTMDSCSNST 600

Query: 601  GCTHTPIACDDKNACTVDSCSNSTGCVHTPLTCDDNNPCTVDSCSNSTGCCHTPINVDDH 660
            GCTHTPIACDDKNACTVDSCSNSTGCVHTPLTCDDNNPCTVDSCSNSTGCCHTPINVDDH
Sbjct: 601  GCTHTPIACDDKNACTVDSCSNSTGCVHTPLTCDDNNPCTVDSCSNSTGCCHTPINVDDH 660

Query: 661  NACTEDKCTQSGGVTHTPIACDDKNACTVDSCSNSTGCCHTPLSCDDNNACTVDSCSNST 720
            NACTEDKCTQSGGVTHTPIACDDKNACTVDSCSNSTGCCHTPLSCDDNNACTVDSCSNST
Sbjct: 661  NACTEDKCTQSGGVTHTPIACDDKNACTVDSCSNSTGCCHTPLSCDDNNACTVDSCSNST 720

Query: 721  GCVHTPINVDDNNACTEDKCTQNGGVTHTPIACDDKNACTVDSCSNSTGCCHTPLKCDDN 780
            GCVHTPINVDDNNACTEDKCTQNGGVTHTPIACDDKNACTVDSCSNSTGCCHTPLKCDDN
Sbjct: 721  GCVHTPINVDDNNACTEDKCTQNGGVTHTPIACDDKNACTVDSCSNSTGCCHTPLKCDDN 780

Query: 781  NPCTVDSCSNSTGCVHTPMNVDDNNACTEDKCTQNGGVTHTPIRCDDLNSCTADSCSNST 840
            NPCTVDSCSNSTGCVHTPMNVDDNNACTEDKCTQNGGVTHTPIRCDDLNSCTADSCSNST
Sbjct: 781  NPCTVDSCSNSTGCVHTPMNVDDNNACTEDKCTQNGGVTHTPIRCDDLNSCTADSCSNST 840

Query: 841  GCVHTPINCDDNNKCTADSCSNSTGCCHTPISCDDNNPCTVDSCSNSTGCCHTPINVDDN 900
            GCVHTPINCDDNNKCTADSCSNSTGCCHTPISCDDNNPCTVDSCSNSTGCCHTPINVDDN
Sbjct: 841  GCVHTPINCDDNNKCTADSCSNSTGCCHTPISCDDNNPCTVDSCSNSTGCCHTPINVDDN 900

Query: 901  NPCTEDKCTQSGGVTHTPIGCNDNNACTVDSCSNSTGCTHTPMKCDDNNPCTIDSCSNST 960
            NPCTEDKCTQSGGVTHTPIGCNDNNACTVDSCSNSTGCTHTPMKCDDNNPCTIDSCSNST
Sbjct: 901  NPCTEDKCTQSGGVTHTPIGCNDNNACTVDSCSNSTGCTHTPMKCDDNNPCTIDSCSNST 960

Query: 961  GCVHTPMNCDDGNFCTLDSCCSTGCTHTPIIIDDNNPCTVDSCCNSTGVVHTPVDCNDNN 1020
            GCVHTPMNCDDGNFCTLDSCCSTGCTHTPIIIDDNNPCTVDSCCNSTGVVHTPVDCNDNN
Sbjct: 961  GCVHTPMNCDDGNFCTLDSCCSTGCTHTPIIIDDNNPCTVDSCCNSTGVVHTPVDCNDNN 1020

Query: 1021 VLTCDYCSIKQGGKCIHVPMTQCKTFGKCGDDL 1053
            VLTCDYCSIKQGGKCIHVPMTQCKTFGKCGDDL
Sbjct: 1021 VLTCDYCSIKQGGKCIHVPMTQCKTFGKCGDDL 1053


