RK16_OEDCA
>RK16_OEDCA#chloroplast#chloroplast GO:0009507(IEA); ribosome
 Identities = 137/137 (100%), Positives = 137/137 (100%)

Query: 1   MLSPKKTKYRKQHRGRMKGKAQRGNKIAYGGFALQAIQPCWITSRQIEAGRRVLTRFVRR 60
           MLSPKKTKYRKQHRGRMKGKAQRGNKIAYGGFALQAIQPCWITSRQIEAGRRVLTRFVRR
Sbjct: 1   MLSPKKTKYRKQHRGRMKGKAQRGNKIAYGGFALQAIQPCWITSRQIEAGRRVLTRFVRR 60

Query: 61  GGKLWIRIFPDKPITMRASGTRMGSGKGSPQYWVAVVKPGRILYEIKGISIKLATRALKI 120
           GGKLWIRIFPDKPITMRASGTRMGSGKGSPQYWVAVVKPGRILYEIKGISIKLATRALKI
Sbjct: 61  GGKLWIRIFPDKPITMRASGTRMGSGKGSPQYWVAVVKPGRILYEIKGISIKLATRALKI 120

Query: 121 AGYKMPIQTKILKPFEN 137
           AGYKMPIQTKILKPFEN
Sbjct: 121 AGYKMPIQTKILKPFEN 137


