PYLS_METBF
>PYLS_METBF#cytoplasm#cytoplasm GO:0005737(IEA);
 Identities = 419/419 (100%), Positives = 419/419 (100%)

Query: 1   MDKKPLDVLISATGLWMSRTGTLHKIKHYEVSRSKIYIEMACGDHLVVNNSRSCRTARAF 60
           MDKKPLDVLISATGLWMSRTGTLHKIKHYEVSRSKIYIEMACGDHLVVNNSRSCRTARAF
Sbjct: 1   MDKKPLDVLISATGLWMSRTGTLHKIKHYEVSRSKIYIEMACGDHLVVNNSRSCRTARAF 60

Query: 61  RHHKYRKTCKRCRVSDEDINNFLTRSTEGKTSVKVKVVSAPKVKKAMPKSVSRAPKPLEN 120
           RHHKYRKTCKRCRVSDEDINNFLTRSTEGKTSVKVKVVSAPKVKKAMPKSVSRAPKPLEN
Sbjct: 61  RHHKYRKTCKRCRVSDEDINNFLTRSTEGKTSVKVKVVSAPKVKKAMPKSVSRAPKPLEN 120

Query: 121 PVSAKASTDTSRSVPSPAKSTPNSPVPTSAPAPSLTRSQLDRVEALLSPEDKISLNIAKP 180
           PVSAKASTDTSRSVPSPAKSTPNSPVPTSAPAPSLTRSQLDRVEALLSPEDKISLNIAKP
Sbjct: 121 PVSAKASTDTSRSVPSPAKSTPNSPVPTSAPAPSLTRSQLDRVEALLSPEDKISLNIAKP 180

Query: 181 FRELESELVTRRKNDFQRLYTNDREDYLGKLERDITKFFVDRDFLEIKSPILIPAEYVER 240
           FRELESELVTRRKNDFQRLYTNDREDYLGKLERDITKFFVDRDFLEIKSPILIPAEYVER
Sbjct: 181 FRELESELVTRRKNDFQRLYTNDREDYLGKLERDITKFFVDRDFLEIKSPILIPAEYVER 240

Query: 241 MGINNDTELSKQIFRVDKNLCLRPMLAPTLYNYLRKLDRILPDPIKIFEVGPCYRKESDG 300
           MGINNDTELSKQIFRVDKNLCLRPMLAPTLYNYLRKLDRILPDPIKIFEVGPCYRKESDG
Sbjct: 241 MGINNDTELSKQIFRVDKNLCLRPMLAPTLYNYLRKLDRILPDPIKIFEVGPCYRKESDG 300

Query: 301 KEHLEEFTMVNFCQMGSGCTRENLESLIKEFLDYLEIDFEIVGDSCMVYGDTLDIMHGDL 360
           KEHLEEFTMVNFCQMGSGCTRENLESLIKEFLDYLEIDFEIVGDSCMVYGDTLDIMHGDL
Sbjct: 301 KEHLEEFTMVNFCQMGSGCTRENLESLIKEFLDYLEIDFEIVGDSCMVYGDTLDIMHGDL 360

Query: 361 ELSSAVVGPVPLDREWGIDKPWIGAGFGLERLLKVMHGFKNIKRASRSESYYNGISTNL 419
           ELSSAVVGPVPLDREWGIDKPWIGAGFGLERLLKVMHGFKNIKRASRSESYYNGISTNL
Sbjct: 361 ELSSAVVGPVPLDREWGIDKPWIGAGFGLERLLKVMHGFKNIKRASRSESYYNGISTNL 419


